********************************************************************************
Product   : Virtuoso(R) XStream Out
Program   : @(#)$CDS: strmout version 6.1.7-64b 11/09/2015 12:41 (sjfbm191) $
          : sub-version  IC6.1.7-64b.78 
Started at: 29-Dec-2022  22:58:53
User Name : work
Host Name : work-eda
Directory : /home/work/Desktop/EE113P/Project
CADENCE Design Systems, Inc.
********************************************************************************
Info: Cellview Rev Num:99,  Tech Rev Num:59


                       Individual Cell Statistics - Basic Objects
---------------------------------------------------------------------------------------------------------------------------------------
Library/Cell/View               Instance Array   Polygon  Rect   Path   PathSeg   Text   TextDisplay   Line   Dot   Arc   Donut   Ellipse 
---------------------------------------------------------------------------------------------------------------------------------------
PROJLib/MA/layout               0        0       0        528    0      0         7      0             0      0     0     0       0       
smic18mmrf/M1_GT/layout         0        0       0        3      0      0         0      0             0      0     0     0       0       
---------------------------------------------------------------------------------------------------------------------------------------

                       Individual Cell Statistics - Advanced Objects
---------------------------------------------------------------------------------------------------------------------------------------
Library/Cell/View               PRBdy    OtherBdy   AreaBlkg   LayerBlkg  AreaHalo   Row   Marker   CustVia   StdVia    CdsGenVia
---------------------------------------------------------------------------------------------------------------------------------------
PROJLib/MA/layout               0        0          0          0          0          0     0        0         8         0        
smic18mmrf/M1_GT/layout         0        0          0          0          0          0     0        0         0         0        
---------------------------------------------------------------------------------------------------------------------------------------

                       Statistics of Layers 
---------------------------------------------------------------------------------------------------------------------------------------
Cadence         Cadence         Stream  Stream   
Layer           Purpose         Layer   Datatype  Polygon  Rect     Path     Text     TextDisplay   Line Dot Arc Donut Ellipse Pathseg
---------------------------------------------------------------------------------------------------------------------------------------
GT              drawing         30      0         0        172      0        0        0             0    0   0   0     0      0      
NW              drawing         14      0         0        1        0        0        0             0    0   0   0     0      0      
AA              drawing         10      0         0        112      0        0        0             0    0   0   0     0      0      
CT              drawing         50      0         0        55       0        0        0             0    0   0   0     0      0      
M1              drawing         61      0         0        107      0        7        0             0    0   0   0     0      0      
SN              drawing         40      0         0        42       0        0        0             0    0   0   0     0      0      
SP              drawing         43      0         0        42       0        0        0             0    0   0   0     0      0      
---------------------------------------------------------------------------------------------------------------------------------------

Summary of Objects Translated:
	Scalar Instances:		0
	Array Instances:		0
	Polygons:			0
	Paths:				0
	Rectangles:			531
	Lines:				0
	Arcs:				0
	Donuts:				0
	Dots:				0
	Ellipses:			0
	Boundaries:			0
	Area Blockages:			0
	Layer Blockages:		0
	Area Halos:			0
	Markers:			0
	Rows:				0
	Standard Vias:			8
	Custom Vias:			0
	CdsGen Vias:			0
	Pathsegs:			0
	Text:				7
	TextDisplay:		0
	Cells:				2
Design Libraries: 

DEFINE PROJLib	/home/work/Desktop/EE113P/Project/PROJLib
DEFINE smic18mmrf	/home/work/EE113/pdk/smic18mmrf/smic18mmrf
